# Generated by Django 3.0.5 on 2020-04-25 09:33

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('date_of_birth', models.DateField()),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=50)),
                ('company_account', models.CharField(blank=True, max_length=26, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{1, 10}$')])),
                ('localisation', models.CharField(max_length=50)),
                ('transfer_data', ckeditor.fields.RichTextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
