# Generated by Django 3.0.5 on 2020-04-25 09:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bartapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='transfer_data',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
