# Generated by Django 3.0.5 on 2020-04-25 09:43

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('bartapp', '0002_auto_20200425_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
