# Generated by Django 3.0.5 on 2020-04-25 09:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bartapp', '0003_auto_20200425_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company_account',
            field=models.CharField(blank=True, max_length=26, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{24, 26}$')]),
        ),
    ]
