# Generated by Django 3.0.5 on 2020-04-25 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bartapp', '0004_auto_20200425_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company_account',
            field=models.CharField(blank=True, max_length=26, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[0-9]{24, 26}')]),
        ),
    ]
