# Generated by Django 3.0.5 on 2020-04-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bartapp', '0005_auto_20200425_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company_account',
            field=models.CharField(blank=True, max_length=26, primary_key=True, serialize=False),
        ),
    ]
