# Generated by Django 3.0.5 on 2020-04-25 09:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bartapp', '0006_auto_20200425_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
