# Generated by Django 3.0.5 on 2020-04-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bartapp', '0007_profile_company_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_short_description',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
