# Generated by Django 3.0.5 on 2020-04-25 11:56

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bartapp', '0008_profile_company_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('date_published', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('category', models.CharField(choices=[('zywnosc', 'Żywność'), ('edukacja', 'Edukacja'), ('kwiaty', ''), ('zdrowie_uroda', 'Zdrowie i uroda'), ('uslugi', 'Usługi'), ('prawo', 'Prawo'), ('odziez_obuwie', 'Odzież i Obuwie'), ('inne', 'Inne')], max_length=20)),
                ('description', ckeditor.fields.RichTextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], max_length=20)),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transfer', models.CharField(choices=[('gotowka', 'Gotówka'), ('przelew', 'Przelew'), ('wymiana', 'Wymiana'), ('wymiana_gotowka', 'Wymiana + gotówka'), ('wymiana_przelew', 'Wymiana + przelew')], max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
