# Generated by Django 3.0.5 on 2020-04-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bartapp', '0009_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='category',
            field=models.CharField(choices=[('zywnosc', 'Żywność'), ('edukacja', 'Edukacja'), ('ogrodnictwo', 'Ogrodnictwo'), ('zdrowie_uroda', 'Zdrowie i uroda'), ('uslugi', 'Usługi'), ('prawo', 'Prawo'), ('odziez_obuwie', 'Odzież i Obuwie'), ('inne', 'Inne')], max_length=20),
        ),
    ]
